server:
  port: 8181
spring:
  application:
    name: spring-boot-login

  datasource:
    url: jdbc:mysql://localhost:3306/loginSystemDb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


